name: Publish

on: [push]

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Publish Docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: bartwillems/rustfuif-frontend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          cache: "true"
